version: "3"

services:
  click_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./dbfiles:/var/lib/clickhouse

  click_client:
    image: yandex/clickhouse-client
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-db.sh"]
    command:
      - infinity

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./redis:/data
